<a href="https://colab.research.google.com/github/prashanthi0801/ElevenSense/blob/main/derma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
model_importance.to_csv('random_forest_feature_importances.csv', index=False)
print("Random Forest feature importances saved to random_forest_feature_importances.csv")

Random Forest feature importances saved to random_forest_feature_importances.csv

In [ ]:
import pandas as pd
data =  pd.read_csv("/content/drive/MyDrive/hospital_skin_lesions/metadata.csv")
data.head()

,isic_id,attribution,copyright_license,age_approx,anatom_site_general,anatom_site_special,benign_malignant,concomitant_biopsy,dermoscopic_type,diagnosis,...,diagnosis_2,diagnosis_3,diagnosis_confirm_type,family_hx_mm,fitzpatrick_skin_type,image_type,lesion_id,patient_id,personal_hx_mm,sex
0,ISIC_0079358,Hospital Italiano de Buenos Aires,CC-BY,35.0,anterior torso,NaN,benign,False,contact polarized,nevus,...,Benign melanocytic proliferations,Nevus,NaN,False,II,dermoscopic,IL_3989348,IP_9328831,False,female
1,ISIC_0086914,Hospital Italiano de Buenos Aires,CC-BY,55.0,upper extremity,NaN,malignant,True,contact polarized,basal cell carcinoma,...,Malignant adnexal epithelial proliferations - ...,Basal cell carcinoma,histopathology,False,II,dermoscopic,IL_9767756,IP_7506563,True,male
2,ISIC_0088904,Hospital Italiano de Buenos Aires,CC-BY,50.0,NaN,NaN,malignant,True,contact polarized,basal cell carcinoma,...,Malignant adnexal epithelial proliferations - ...,Basal cell carcinoma,histopathology,False,II,dermoscopic,IL_8711401,IP_0222733,False,female
3,ISIC_0094098,Hospital Italiano de Buenos Aires,CC-BY,65.0,posterior torso,NaN,malignant,True,NaN,melanoma,...,Malignant melanocytic proliferations (Melanoma),"Melanoma, NOS",histopathology,False,II,clinical: overview,IL_6961144,IP_1218261,True,male
4,ISIC_0095134,Hospital Italiano de Buenos Aires,CC-BY,70.0,anterior torso,NaN,malignant,True,contact polarized,melanoma,...,Malignant melanocytic proliferations (Melanoma),"Melanoma, NOS",histopathology,False,I,dermoscopic,IL_4530268,IP_8235588,True,female

In [ ]:
data.describe()
# data.info()

        age_approx
count  1611.000000
mean     59.615146
std      18.697683
min      20.000000
25%      45.000000
50%      65.000000
75%      75.000000
max      85.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1616 entries, 0 to 1615
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   isic_id                 1616 non-null   object
 1   attribution             1616 non-null   object
 2   copyright_license       1616 non-null   object
 3   age_approx              1611 non-null   float64
 4   anatom_site_general     1506 non-null   object
 5   anatom_site_special     31 non-null     object
 6   benign_malignant        1616 non-null   object
 7   concomitant_biopsy      1616 non-null   bool
 8   dermoscopic_type        1270 non-null   object
 9   diagnosis               1616 non-null   object
 10  diagnosis_1             1616 non-null   object
 11  diagnosis_2             1616 non-null   object
 12  diagnosis_3             1565 non-null   object
 13  diagnosis_confirm_type  1038 non-null   object
 14  family_hx_mm            759 non-null    object
 15  fitzpatrick_skin_type   1499 non-null   object
 16  image_type              1616 non-null   object
 17  lesion_id               1616 non-null   object
 18  patient_id              1616 non-null   object
 19  personal_hx_mm          885 non-null    object
 20  sex                     1611 non-null   object
dtypes: bool(1), float64(1), object(19)
memory usage: 254.2+ KB

In [ ]:
data.isnull().sum()

isic_id                      0
attribution                  0
copyright_license            0
age_approx                   5
anatom_site_general        110
anatom_site_special       1585
benign_malignant             0
concomitant_biopsy           0
dermoscopic_type           346
diagnosis                    0
diagnosis_1                  0
diagnosis_2                  0
diagnosis_3                 51
diagnosis_confirm_type     578
family_hx_mm               857
fitzpatrick_skin_type      117
image_type                   0
lesion_id                    0
patient_id                   0
personal_hx_mm             731
sex                          5
dtype: int64

In [ ]:
print(data.size)
print(data.shape)
print(data.ndim)

33936
(1616, 21)
2

In [ ]:
data[data['age_approx'].isnull()]
# print()

,isic_id,attribution,copyright_license,age_approx,anatom_site_general,anatom_site_special,benign_malignant,concomitant_biopsy,dermoscopic_type,diagnosis,...,diagnosis_2,diagnosis_3,diagnosis_confirm_type,family_hx_mm,fitzpatrick_skin_type,image_type,lesion_id,patient_id,personal_hx_mm,sex
510,ISIC_3222130,Hospital Italiano de Buenos Aires,CC-BY,NaN,anterior torso,NaN,malignant,True,NaN,basal cell carcinoma,...,Malignant adnexal epithelial proliferations - ...,Basal cell carcinoma,histopathology,NaN,II,clinical: overview,IL_9896383,IP_0095265,NaN,female
618,ISIC_3885770,Hospital Italiano de Buenos Aires,CC-BY,NaN,head/neck,NaN,benign,True,contact polarized,nevus,...,Benign melanocytic proliferations,Nevus,histopathology,NaN,NaN,dermoscopic,IL_0339787,IP_1599385,NaN,male
679,ISIC_4292551,Hospital Italiano de Buenos Aires,CC-BY,NaN,head/neck,NaN,benign,True,contact polarized,actinic keratosis,...,Indeterminate epidermal proliferations,Solar or actinic keratosis,histopathology,NaN,NaN,dermoscopic,IL_4204665,IP_1801534,NaN,female
1101,ISIC_6926022,Hospital Italiano de Buenos Aires,CC-BY,NaN,lower extremity,NaN,benign,True,contact polarized,dermatofibroma,...,Benign soft tissue proliferations - Fibro-hist...,Dermatofibroma,histopathology,NaN,NaN,dermoscopic,IL_4195290,IP_1751755,NaN,female
1248,ISIC_7838914,Hospital Italiano de Buenos Aires,CC-BY,NaN,head/neck,NaN,malignant,True,contact polarized,basal cell carcinoma,...,Malignant adnexal epithelial proliferations - ...,Basal cell carcinoma,histopathology,NaN,NaN,dermoscopic,IL_7619293,IP_2179904,NaN,male

In [ ]:
data=data.dropna(subset=["age_approx"])
# data["age_approx"].isnull().sum()
data["anatom_site_general"].fillna("unknown",inplace=True)
data["dermoscopic_type"].fillna("unknown",inplace=True)
data.drop(columns=["anatom_site_special"],inplace=True)
data["diagnosis_3"].fillna("unknown", inplace=True)
data["diagnosis_confirm_type"].fillna("unknown",inplace=True)
data["family_hx_mm"].fillna("unknown",inplace=True)
data["fitzpatrick_skin_type"].fillna(
    "unknown",
    inplace=True
)
data["personal_hx_mm"].fillna("unknown",inplace=True)
data["sex"].fillna("unknown",inplace=True)

/tmp/ipython-input-312397648.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["anatom_site_general"].fillna("unknown",inplace=True)
/tmp/ipython-input-312397648.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["dermoscopic_type"].fillna("unknown",inplace=True)
/tmp/ipython-input-312397648.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["diagnosis_3"].fillna("unknown", inplace=True)
/tmp/ipython-input-312397648.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["diagnosis_confirm_type"].fillna("unknown",inplace=True)
/tmp/ipython-input-312397648.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["family_hx_mm"].fillna("unknown",inplace=True)
/tmp/ipython-input-312397648.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["fitzpatrick_skin_type"].fillna(
/tmp/ipython-input-312397648.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["personal_hx_mm"].fillna("unknown",inplace=True)
/tmp/ipython-input-312397648.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["sex"].fillna("unknown",inplace=True)

In [ ]:
data.to_csv('cleaned_data1.csv', index=False)
# print("Cleaned data saved to cleaned_data.csv

In [ ]:
data.isnull().sum()

isic_id                   0
attribution               0
copyright_license         0
age_approx                0
anatom_site_general       0
benign_malignant          0
concomitant_biopsy        0
dermoscopic_type          0
diagnosis                 0
diagnosis_1               0
diagnosis_2               0
diagnosis_3               0
diagnosis_confirm_type    0
family_hx_mm              0
fitzpatrick_skin_type     0
image_type                0
lesion_id                 0
patient_id                0
personal_hx_mm            0
sex                       0
dtype: int64

In [ ]:
data["concomitant_biopsy"] = data["concomitant_biopsy"].astype(int)
DROP_COLS = [
    "patient_id",
    "lesion_id",
    "isic_id",
    "attribution",
    "copyright_license",
    "anatom_site_general"

]

data.drop(columns=DROP_COLS , inplace=True)
data_clean=data

In [ ]:
y = data_clean["benign_malignant"].map({"benign": 0, "malignant": 1})
X = data_clean.drop(columns=["benign_malignant"])

In [ ]:
X.isnull().sum()
# x.info()

age_approx                0
concomitant_biopsy        0
dermoscopic_type          0
diagnosis                 0
diagnosis_1               0
diagnosis_2               0
diagnosis_3               0
diagnosis_confirm_type    0
family_hx_mm              0
fitzpatrick_skin_type     0
image_type                0
personal_hx_mm            0
sex                       0
dtype: int64

In [ ]:
from sklearn.feature_selection import mutual_info_classif
import pandas as pd
X_encoded = pd.get_dummies(X,drop_first=True)
mi_scores = mutual_info_classif(X_encoded,y,random_state=42)
mi_df = pd.DataFrame({
    "Feature": X_encoded.columns,
    "Information_Gain": mi_scores
}).sort_values(by="Information_Gain", ascending=False)
print(X_encoded.columns.tolist())
mi_df.head(10)
# mi_df.shape

['age_approx', 'concomitant_biopsy', 'dermoscopic_type_unknown', 'diagnosis_basal cell carcinoma', 'diagnosis_dermatofibroma', 'diagnosis_lichenoid keratosis', 'diagnosis_melanoma', 'diagnosis_nevus', 'diagnosis_seborrheic keratosis', 'diagnosis_solar lentigo', 'diagnosis_squamous cell carcinoma', 'diagnosis_vascular lesion', 'diagnosis_1_Indeterminate', 'diagnosis_1_Malignant', 'diagnosis_2_Benign melanocytic proliferations', 'diagnosis_2_Benign soft tissue proliferations - Fibro-histiocytic', 'diagnosis_2_Benign soft tissue proliferations - Vascular', 'diagnosis_2_Indeterminate epidermal proliferations', 'diagnosis_2_Malignant adnexal epithelial proliferations - Follicular', 'diagnosis_2_Malignant epidermal proliferations', 'diagnosis_2_Malignant melanocytic proliferations (Melanoma)', 'diagnosis_3_Dermatofibroma', 'diagnosis_3_Lichen planus like keratosis', 'diagnosis_3_Melanoma, NOS', 'diagnosis_3_Nevus', 'diagnosis_3_Seborrheic keratosis', 'diagnosis_3_Solar lentigo', 'diagnosis_3_Solar or actinic keratosis', 'diagnosis_3_Squamous cell carcinoma, NOS', 'diagnosis_3_unknown', 'diagnosis_confirm_type_single image expert consensus', 'diagnosis_confirm_type_unknown', 'family_hx_mm_True', 'family_hx_mm_unknown', 'fitzpatrick_skin_type_II', 'fitzpatrick_skin_type_III', 'fitzpatrick_skin_type_IV', 'fitzpatrick_skin_type_unknown', 'image_type_clinical: overview', 'image_type_dermoscopic', 'personal_hx_mm_True', 'personal_hx_mm_unknown', 'sex_male', 'sex_unknown']

                                              Feature  Information_Gain
13                              diagnosis_1_Malignant          0.690996
24                                  diagnosis_3_Nevus          0.339083
7                                     diagnosis_nevus          0.336582
14      diagnosis_2_Benign melanocytic proliferations          0.336264
31                     diagnosis_confirm_type_unknown          0.328538
1                                  concomitant_biopsy          0.309934
18  diagnosis_2_Malignant adnexal epithelial proli...          0.199580
3                      diagnosis_basal cell carcinoma          0.183715
0                                          age_approx          0.174514
23                          diagnosis_3_Melanoma, NOS          0.134214

In [ ]:
columns_with_unknown_encoding = [col for col in X_encoded.columns if 'unknown' in col]
print("One-hot encoded columns related to 'unknown' values:")
columns_with_unknown_encoding

One-hot encoded columns related to 'unknown' values:

['dermoscopic_type_unknown',
 'diagnosis_3_unknown',
 'diagnosis_confirm_type_unknown',
 'family_hx_mm_unknown',
 'fitzpatrick_skin_type_unknown',
 'personal_hx_mm_unknown',
 'sex_unknown']

In [ ]:
mi_df[mi_df['Feature'].isin(columns_with_unknown_encoding)]

                           Feature  Information_Gain
31  diagnosis_confirm_type_unknown          0.328538
33            family_hx_mm_unknown          0.054735
41          personal_hx_mm_unknown          0.051183
29             diagnosis_3_unknown          0.020186
2         dermoscopic_type_unknown          0.012156
37   fitzpatrick_skin_type_unknown          0.000000
43                     sex_unknown          0.000000

In [ ]:
from sklearn.feature_selection import chi2

X_cat = pd.get_dummies(X.select_dtypes(include="object"))

chi_scores, p_values = chi2(X_cat, y)

chi_df = pd.DataFrame({
    "Feature": X_cat.columns,
    "Chi2_Score": chi_scores,
    "p_value": p_values
}).sort_values(by="Chi2_Score", ascending=False)

chi_df.head(10)

,Feature,Chi2_Score,p_value
14,diagnosis_1_Malignant,862.000000,1.789626e-189
12,diagnosis_1_Benign,695.127610,3.429593e-153
16,diagnosis_2_Benign melanocytic proliferations,522.214617,1.395483e-115
7,diagnosis_nevus,522.214617,1.395483e-115
27,diagnosis_3_Nevus,522.214617,1.395483e-115
35,diagnosis_confirm_type_unknown,502.229698,3.110535e-111
23,diagnosis_3_Basal cell carcinoma,388.993324,1.370984e-86
20,diagnosis_2_Malignant adnexal epithelial proli...,388.993324,1.370984e-86
3,diagnosis_basal cell carcinoma,388.993324,1.370984e-86
26,"diagnosis_3_Melanoma, NOS",291.169559,2.765169e-65

In [ ]:
top10_mi_features = set(
    mi_df
    .sort_values(by="Information_Gain", ascending=False)
    .head(10)["Feature"]
)
top10_mi_features

{'age_approx',
 'concomitant_biopsy',
 'diagnosis_1_Malignant',
 'diagnosis_2_Benign melanocytic proliferations',
 'diagnosis_2_Malignant adnexal epithelial proliferations - Follicular',
 'diagnosis_3_Melanoma, NOS',
 'diagnosis_3_Nevus',
 'diagnosis_basal cell carcinoma',
 'diagnosis_confirm_type_unknown',
 'diagnosis_nevus'}

In [ ]:
top10_chi_features = set(
    chi_df[chi_df["p_value"] < 0.05]
    .sort_values(by="Chi2_Score", ascending=False)
    .head(10)["Feature"]
)
top10_chi_features

{'diagnosis_1_Benign',
 'diagnosis_1_Malignant',
 'diagnosis_2_Benign melanocytic proliferations',
 'diagnosis_2_Malignant adnexal epithelial proliferations - Follicular',
 'diagnosis_3_Basal cell carcinoma',
 'diagnosis_3_Melanoma, NOS',
 'diagnosis_3_Nevus',
 'diagnosis_basal cell carcinoma',
 'diagnosis_confirm_type_unknown',
 'diagnosis_nevus'}

In [ ]:
chi_df[chi_df['Feature'].isin(columns_with_unknown_encoding)]

                           Feature  Chi2_Score        p_value
35  diagnosis_confirm_type_unknown  502.229698  3.110535e-111
38            family_hx_mm_unknown   93.641021   3.782662e-22
49          personal_hx_mm_unknown   56.999457   4.359323e-14
32             diagnosis_3_unknown   44.314385   2.796537e-11
1         dermoscopic_type_unknown   37.325879   9.994943e-10
43   fitzpatrick_skin_type_unknown    4.734829   2.955778e-02
52                     sex_unknown    2.256559   1.330494e-01

In [ ]:
common_features = list(top10_mi_features.intersection(top10_chi_features))
common_features

['diagnosis_1_Malignant',
 'diagnosis_confirm_type_unknown',
 'diagnosis_3_Nevus',
 'diagnosis_2_Benign melanocytic proliferations',
 'diagnosis_basal cell carcinoma',
 'diagnosis_2_Malignant adnexal epithelial proliferations - Follicular',
 'diagnosis_nevus',
 'diagnosis_3_Melanoma, NOS']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.3, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (1127, 44)
X_test shape: (484, 44)
y_train shape: (1127,)
y_test shape: (484,)

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [ ]:
from sklearn.metrics import classification_report, roc_auc_score

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       250
           1       1.00      1.00      1.00       234

    accuracy                           1.00       484
   macro avg       1.00      1.00      1.00       484
weighted avg       1.00      1.00      1.00       484

ROC-AUC: 1.0

In [ ]:

# LR for directional intuition
# +ve increases odds of malignancy
# -ve decreases odds of malignancy

In [ ]:
coef_df = pd.DataFrame({
    'feature': X_encoded.columns,
    'coefficient': model.coef_[0]
}).sort_values(by='coefficient', ascending=False)

coef_df

                                              feature  coefficient
13                              diagnosis_1_Malignant     3.659483
3                      diagnosis_basal cell carcinoma     1.646246
18  diagnosis_2_Malignant adnexal epithelial proli...     1.646246
6                                  diagnosis_melanoma     1.090612
20  diagnosis_2_Malignant melanocytic proliferatio...     1.090612
23                          diagnosis_3_Melanoma, NOS     1.090612
28           diagnosis_3_Squamous cell carcinoma, NOS     0.922624
19     diagnosis_2_Malignant epidermal proliferations     0.922624
10                  diagnosis_squamous cell carcinoma     0.922624
1                                  concomitant_biopsy     0.919703
40                                personal_hx_mm_True     0.294279
33                               family_hx_mm_unknown     0.181512
34                           fitzpatrick_skin_type_II     0.137186
41                             personal_hx_mm_unknown     0.083513
42                                           sex_male     0.040783
0                                          age_approx     0.024981
2                            dermoscopic_type_unknown     0.017391
32                                  family_hx_mm_True     0.008076
38                      image_type_clinical: overview     0.004898
43                                        sex_unknown    -0.005888
36                           fitzpatrick_skin_type_IV    -0.016582
39                             image_type_dermoscopic    -0.025836
30  diagnosis_confirm_type_single image expert con...    -0.026735
37                      fitzpatrick_skin_type_unknown    -0.041121
22           diagnosis_3_Lichen planus like keratosis    -0.063662
5                       diagnosis_lichenoid keratosis    -0.063662
35                          fitzpatrick_skin_type_III    -0.122757
11                          diagnosis_vascular lesion    -0.363830
29                                diagnosis_3_unknown    -0.363830
16  diagnosis_2_Benign soft tissue proliferations ...    -0.363830
26                          diagnosis_3_Solar lentigo    -0.414955
9                             diagnosis_solar lentigo    -0.414955
15  diagnosis_2_Benign soft tissue proliferations ...    -0.443998
21                         diagnosis_3_Dermatofibroma    -0.443998
4                            diagnosis_dermatofibroma    -0.443998
12                          diagnosis_1_Indeterminate    -0.629324
17  diagnosis_2_Indeterminate epidermal proliferat...    -0.629324
27             diagnosis_3_Solar or actinic keratosis    -0.629324
25                   diagnosis_3_Seborrheic keratosis    -0.827269
8                      diagnosis_seborrheic keratosis    -0.827269
31                     diagnosis_confirm_type_unknown    -0.901413
7                                     diagnosis_nevus    -0.924889
24                                  diagnosis_3_Nevus    -0.924889
14      diagnosis_2_Benign melanocytic proliferations    -0.924889

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=300,random_state=42, class_weight='balanced')
model.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=300,
                       random_state=42)

In [ ]:
model_importance = pd.DataFrame({
    'feature': X_encoded.columns,
    'importance': model.feature_importances_
}).sort_values(by='importance', ascending=False)

model_importance

                                              feature    importance
13                              diagnosis_1_Malignant  2.881454e-01
1                                  concomitant_biopsy  1.080944e-01
14      diagnosis_2_Benign melanocytic proliferations  8.580923e-02
31                     diagnosis_confirm_type_unknown  8.089316e-02
24                                  diagnosis_3_Nevus  7.958208e-02
7                                     diagnosis_nevus  6.317045e-02
18  diagnosis_2_Malignant adnexal epithelial proli...  4.351505e-02
3                      diagnosis_basal cell carcinoma  3.982586e-02
6                                  diagnosis_melanoma  2.562182e-02
20  diagnosis_2_Malignant melanocytic proliferatio...  2.421547e-02
23                          diagnosis_3_Melanoma, NOS  1.734477e-02
0                                          age_approx  1.570405e-02
28           diagnosis_3_Squamous cell carcinoma, NOS  1.464787e-02
10                  diagnosis_squamous cell carcinoma  1.385482e-02
8                      diagnosis_seborrheic keratosis  1.231399e-02
19     diagnosis_2_Malignant epidermal proliferations  1.219618e-02
25                   diagnosis_3_Seborrheic keratosis  1.156654e-02
12                          diagnosis_1_Indeterminate  1.066428e-02
27             diagnosis_3_Solar or actinic keratosis  7.568514e-03
17  diagnosis_2_Indeterminate epidermal proliferat...  7.323521e-03
15  diagnosis_2_Benign soft tissue proliferations ...  6.013584e-03
21                         diagnosis_3_Dermatofibroma  5.087757e-03
4                            diagnosis_dermatofibroma  5.041881e-03
33                               family_hx_mm_unknown  4.576790e-03
11                          diagnosis_vascular lesion  3.256088e-03
29                                diagnosis_3_unknown  2.442764e-03
16  diagnosis_2_Benign soft tissue proliferations ...  2.200716e-03
26                          diagnosis_3_Solar lentigo  1.830659e-03
41                             personal_hx_mm_unknown  1.622286e-03
9                             diagnosis_solar lentigo  1.430920e-03
32                                  family_hx_mm_True  1.383916e-03
40                                personal_hx_mm_True  8.629480e-04
35                          fitzpatrick_skin_type_III  8.105032e-04
34                           fitzpatrick_skin_type_II  4.593749e-04
2                            dermoscopic_type_unknown  2.782395e-04
38                      image_type_clinical: overview  2.103319e-04
42                                           sex_male  1.196823e-04
36                           fitzpatrick_skin_type_IV  8.208378e-05
39                             image_type_dermoscopic  6.810914e-05
37                      fitzpatrick_skin_type_unknown  6.200661e-05
30  diagnosis_confirm_type_single image expert con...  6.088683e-05
5                       diagnosis_lichenoid keratosis  3.378426e-05
22           diagnosis_3_Lichen planus like keratosis  7.303265e-06
43                                        sex_unknown  3.041307e-16